#!/bin/bash

if ! python3 --version; then
    echo "ver. >= python3.6 required"
    exit 1
fi

agsdir=$(dirname $0)
echo "Checking for updates..."
git -C $agsdir fetch origin
git -C $agsdir pull
python3 $agsdir/agscore.py $@
