#!/bin/bash

pyver="$(python3 -V 2>&1)"
if [ $? -ne 0 ]; then
    echo "Python 3 is not installed"
    exit 1
fi

agsdir=$(dirname $0)
echo "Checking for updates..."
git -C $agsdir fetch origin
git -C $agsdir pull
python3 $agsdir/agscore.py $@
