# All paths must be relative to Rails.root
path:
  uploads_root: public/uploads

# Libraries
library:
  cs-checkstyle:
    source: https://github.ncsu.edu/engr-csc116-staff/cs-checkstyle
  drawing-panel:
    source: http://www.buildingjavaprograms.com/drawingpanel/DrawingPanel.java
    version: 4.04
  hamcrest-core:
    version: 1.3
  junit4:
    version: 4.12
